<a href="https://colab.research.google.com/github/kallamadi626/kallamadi626/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install numpy

In [3]:
import numpy
print(numpy. __version__)

1.26.4


In [4]:
import numpy as np

In [5]:
a=np.array
print(a)

<built-in function array>


In [8]:
a=np.array([1,2,3])
print(a)
print(a.dtype)
print(type(a))

[1 2 3]
int64
<class 'numpy.ndarray'>


In [9]:
a=np.array([[1,2,3],[7,8,9]])
print(a)
print(a.dtype)
print(type(a))


[[1 2 3]
 [7 8 9]]
int64
<class 'numpy.ndarray'>


In [12]:
a=np.array([[1,2,3,],[4,5,6],[6,7,8]])
print(a)
print(a.dtype)
print(type(a))
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
int64
<class 'numpy.ndarray'>
2


In [13]:
a=np.array([[1,2,3,4,5,6]])
print(a.size)
print(a.shape)

6
(1, 6)


In [14]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)


In [18]:
a=np.array([[1,2,],[3,4],[4,5]])
print('Original array')
print(a)

a=a.reshape(2,3)
print('Reshaped array')
print(a)

Original array
[[1 2]
 [3 4]
 [4 5]]
Reshaped array
[[1 2 3]
 [4 4 5]]


In [16]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[0,1])
print(a[2,1])


[[1 2]
 [3 4]
 [5 6]]
2
6


In [19]:
a=np.array([1,2,3,50,4,45,4])
print(a)
print('maximum number:', a.max())
print('minimum number:', a.min())
print('sum of all values:', a.sum())

[ 1  2  3 50  4 45  4]
maximum number: 50
minimum number: 1
sum of all values: 109


In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
b=np.ones((3,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print("max number in column:",a.max(axis=0))

[[1 2]
 [3 4]
 [5 6]]
max number in column: [5 6]


In [25]:
a=np.random.randn(3,4)
print(a)

[[-1.83151925 -0.86982008  0.19300251 -1.63220843]
 [ 1.41815342  0.01621503 -0.38353444 -0.25029225]
 [ 0.25523995  1.65139574 -2.20046004  0.59336968]]


In [26]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[10,5,15]])
print("sum of a and b:\n", a+b)
print("substraction of a and b:", a-b)
print("product of a and b:\n", a*b)
print("division of a and b:\n", a/b)

sum of a and b:
 [[ 2  4  6]
 [14 10 21]]
substraction of a and b: [[ 0  0  0]
 [-6  0 -9]]
product of a and b:
 [[ 1  4  9]
 [40 25 90]]
division of a and b:
 [[1.  1.  1. ]
 [0.4 1.  0.4]]


In [28]:
# Ranging function  in numpy ---> range()
print(np.arange(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(np.arange(12))